[package]
name = "bc-rand"
version = "0.4.0"
edition = "2024"
description = "Blockchain Commons Random Number Utilities."
authors = ["Blockchain Commons"]
repository = "https://github.com/BlockchainCommons/bc-rand-rust"
readme = "README.md"
license = "BSD-2-Clause-Patent"
documentation = "https://docs.rs/bc-rand"
keywords = ["random", "testing", "security"]                     # Up to five
categories = ["algorithms"]                                      # https://crates.io/category_slugs

[dependencies]
rand = "^0.9.2"
rand_core = "^0.9.3"
getrandom = "^0.3.3"
rand_xoshiro = "^0.7.0"
num-traits = "^0.2.19"
lazy_static = "^1.5.0"

[dev-dependencies]
hex-literal = "^1.0.0"
version-sync = "^0.9"
